name: CI/CD Github Actions
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install pytest, pytest-cov
        run: |
          python -m pip install --upgrade pytest pytest-cov readchar
      - name: Run test suite
        run: |
          pytest -v --cov --cov-report=xml --cov-report=html
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  

  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install pytest pytest-cov coveralls readchar
      - name: Run test suite
        run: |
          pytest -v --cov --cov-report=xml --cov-report=html test_main.py
      - run: coverage json
      - name: Coveralls
        run: COVERALLS_REPO_TOKEN=${{ secrets.coveralls_token }} coveralls
